imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PSUserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        #save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        save_path: "/home/fafa/Documents/var_session_symfony/"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
      #  - 'bootstrap_3_horizontal_layout.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
# fos_user Configuration    
fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    PS\UserBundle\Entity\User # La classe de l'entité User que nous utilisons

assetic:
  debug:          '%kernel.debug%'
  use_controller: '%kernel.debug%'
  filters:
    cssrewrite: ~
    jsqueeze:   ~
    scssphp:
      formatter: 'Leafo\ScssPhp\Formatter\Compressed'
      
# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
#easy_admin
easy_admin:
    site_name: 'Pédiatrie'
    list:
        actions: ['delete', 'edit', 'new', 'search', 'show']
    design:
        menu:
            - { label: 'Retour au site', route: 'root' }
            - { entity: 'User', default: true, label: 'users', icon: 'user-md' }
            - label: 'customers'
              icon: 'users'
              children:
                - Mother
                - Father
                - Patient
                - Address
            - label: 'consultations'
              icon: 'stethoscope'
              children:
                - { entity: 'Consultation', label: 'consultations' }
    entities:
        Mother:
            class : PS\CustomerBundle\Entity\Mother
        Father:
            class : PS\CustomerBundle\Entity\Father
        Patient:
            class : PS\CustomerBundle\Entity\Patient
        Address:
            class : PS\CustomerBundle\Entity\Address
        Consultation:
            class : PS\ConsultationBundle\Entity\Consultation
            
        User:
            class : PS\UserBundle\Entity\User
            list:
                fields: 
                    - { property: 'id' }
                    - { property: 'username', label: 'user.username' }
                    - { property: 'email', label: 'user.email' }
                    - { property: 'enabled', label: 'user.actif'}
                    - { property: 'lastLogin', label: 'user.lastlogin'}
                    - { property: 'roles', label: 'user.roles'}
            form: 
                form_options: { validation_groups: ['Registration'] }
                fields: 
                    - { property: 'username', label: 'user.username' }
                    - { property: 'email', type: 'email', label: 'user.email' }
                    - { property: 'plainPassword', type: 'password', label: 'user.password' }
                    - { property: 'enabled', label: 'user.actif'}
                    - property: 'roles'
                      label: 'user.roles'
                      type: 'choice'
                      type_options:
                        expanded: true
                        multiple: true
                        choices: { 'Administrateur': 'ROLE_ADMIN', 'Docteur': 'ROLE_DOCTOR', 'Secrétaire': 'ROLE_SECRETARY' }
            edit:
                form_options: { validation_groups: ['Profile'] }
                fields: 
                    - { property: 'plainPassword', type: 'password', label: 'user.password', type_options: { required: false } }
