#### Ordre
#### PERSON, PATIENT, CONSULTATION, WARRANTYCOMPANY, VOUCHER, SUBSCRIPTION_INFO, PAYMENT 



#### PERSON

CREATE TABLE  "P_PERSON" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50), 
	"SURNAME" VARCHAR2(50), 
	"SEX" VARCHAR2(1), 
	"BORN" DATE, 
	"TYPE" VARCHAR2(10), 
	"PHONE" NUMBER, 
	 CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "PERSON_CK1" CHECK (SEX IN ('M','F')) ENABLE, 
	 CONSTRAINT "PERSON_CK2" CHECK (TYPE IN ('MOTHER','FATHER','CHILD')) ENABLE
   ) ;


CREATE OR REPLACE TRIGGER  "BI_PERSON" 
  before insert on "P_PERSON"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "PERSON_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_PERSON" ENABLE;




######## PATIENT

CREATE TABLE  "P_PATIENT" 
   (	"ID_PATIENT" NUMBER NOT NULL ENABLE, 
	"ID_FATHER" NUMBER, 
	"ID_MOTHER" NUMBER, 
	"ADDRESS" VARCHAR2(500), 
	"PERSONELDISEASESHISTORY" VARCHAR2(500), 
	"FAMILYDISEASESHISTORY" VARCHAR2(500), 
	 CONSTRAINT "PATIENT_PK" PRIMARY KEY ("ID_PATIENT") ENABLE
   ) ;ALTER TABLE  "P_PATIENT" ADD CONSTRAINT "PATIENT_FK" FOREIGN KEY ("ID_PATIENT")
	  REFERENCES  "P_PERSON" ("ID") ENABLE;ALTER TABLE  "P_PATIENT" ADD CONSTRAINT "PATIENT_FK2" FOREIGN KEY ("ID_FATHER")
	  REFERENCES  "P_PERSON" ("ID") ENABLE;ALTER TABLE  "P_PATIENT" ADD CONSTRAINT "PATIENT_FK3" FOREIGN KEY ("ID_MOTHER")
	  REFERENCES  "P_PERSON" ("ID") ENABLE;
	  
	  

	  
#### CONSULTATION

CREATE TABLE  "P_CONSULTATION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_PATIENT" NUMBER NOT NULL ENABLE, 
	"DATE_C" DATE, 
	"INTERVIEW" VARCHAR2(500), 
	"CLINICEXAMINATION" VARCHAR2(500), 
	"CONCLUSION" VARCHAR2(500), 
	"CHECKUP" VARCHAR2(500), 
	"DIAGNOSIC" VARCHAR2(500), 
	"TREATMENT" VARCHAR2(500), 
	 CONSTRAINT "CONSULTATION_PK" PRIMARY KEY ("ID") ENABLE
   ) ;ALTER TABLE  "P_CONSULTATION" ADD CONSTRAINT "CONSULTATION_FK" FOREIGN KEY ("ID_PATIENT")
	  REFERENCES  "P_PATIENT" ("ID_PATIENT") ENABLE;


CREATE OR REPLACE TRIGGER  "BI_CONSULTATION" 
  before insert on "P_CONSULTATION"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "CONSULTATION_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_CONSULTATION" ENABLE;





##### WARRANTYCOMPANY

CREATE TABLE  "P_WARRANTYCOMPANY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "WARRANTYCOMPANY_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "WARRANTYCOMPANY_CK1" CHECK (TYPE IN ('IPM','INSURANCE','OTHER') ) ENABLE, 
	 CONSTRAINT "WARRANTYCOMPANY_UK1" UNIQUE ("NAME", "TYPE") ENABLE
   ) ;


CREATE OR REPLACE TRIGGER  "BI_WARRANTYCOMPANY" 
  before insert on "P_WARRANTYCOMPANY"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "WARRANTYCOMPANY_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_WARRANTYCOMPANY" ENABLE;





##### VOUCHER

CREATE TABLE  "P_VOUCHER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_SUBSCRIBER" NUMBER NOT NULL ENABLE, 
	"ID_DEPENDENT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "VOUCHER_PK" PRIMARY KEY ("ID") ENABLE
   ) ;ALTER TABLE  "P_VOUCHER" ADD CONSTRAINT "VOUCHER_FK2" FOREIGN KEY ("ID_DEPENDENT")
	  REFERENCES  "P_PATIENT" ("ID_PATIENT") ENABLE;ALTER TABLE  "P_VOUCHER" ADD CONSTRAINT "VOUCHER_FK4" FOREIGN KEY ("ID_SUBSCRIBER")
	  REFERENCES  "P_PERSON" ("ID") ENABLE;


CREATE OR REPLACE TRIGGER  "BI_VOUCHER" 
  before insert on "P_VOUCHER"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "VOUCHER_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_VOUCHER" ENABLE;

#### SUBSCRIPTION_INFO

CREATE TABLE  "P_SUBSCRIPTION_INFO" 
   (	"ID_SUBSCRIBER" NUMBER NOT NULL ENABLE, 
	"ID_WARRANTYCOMPANY" NUMBER NOT NULL ENABLE, 
	"IDENTIFICATION" NUMBER NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(100), 
	"PROFESSION" VARCHAR2(100), 
	 CONSTRAINT "SUBSCRIPTION_INFO_PK" PRIMARY KEY ("ID_SUBSCRIBER") ENABLE
   ) ;ALTER TABLE  "P_SUBSCRIPTION_INFO" ADD CONSTRAINT "SUBSCRIPTION_INFO_FK" FOREIGN KEY ("ID_SUBSCRIBER")
	  REFERENCES  "P_PERSON" ("ID") ENABLE;ALTER TABLE  "P_SUBSCRIPTION_INFO" ADD CONSTRAINT "SUBSCRIPTION_INFO_FK2" FOREIGN KEY ("ID_WARRANTYCOMPANY")
	  REFERENCES  "P_WARRANTYCOMPANY" ("ID") ENABLE;



### PAYMENT

CREATE TABLE  "P_PAYMENT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CONSULTATION" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"PAYMENT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "P_PAYMENT_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "P_PAYMENT_CK1" CHECK (TYPE IN ('CASH','VOUCHER', 'CHEQUE', 'CREDITCARD', 'OTHER') ) ENABLE
   ) ;ALTER TABLE  "P_PAYMENT" ADD CONSTRAINT "P_PAYMENT_FK" FOREIGN KEY ("ID_CONSULTATION")
	  REFERENCES  "P_CONSULTATION" ("ID") ENABLE;


CREATE OR REPLACE TRIGGER  "BI_P_PAYMENT" 
  before insert on "P_PAYMENT"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "P_PAYMENT_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_P_PAYMENT" ENABLE;

### USER

CREATE TABLE  "P_USER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100), 
	"KEY" NUMBER, 
	"TITLE" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"SURNAME" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(500), 
	"PHONE" NUMBER, 
	"OTHER" VARCHAR2(500), 
	 CONSTRAINT "P_USER_PK" PRIMARY KEY ("ID") ENABLE
   ) ;


CREATE OR REPLACE TRIGGER  "BI_P_USER" 
  before insert on "P_USER"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "P_USER_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_P_USER" ENABLE;










