<?php

namespace PS\ConsultationBundle\Repository;

/**
 * ClinicExamConstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClinicExamConstRepository extends \Doctrine\ORM\EntityRepository
{
}
