ps_consultation_homepage:
    path:     /
    defaults: { _controller: PSConsultationBundle:Consultation:index }
    
    
ps_consultation_new:
    path:     /new/{id}
    defaults: { _controller: PSConsultationBundle:Consultation:new }
    requirements:
        id: \d+

ps_consultation_edit:
    path:     /edit/{id}
    defaults: { _controller: PSConsultationBundle:Consultation:edit }
    requirements:
        id: \d+

ps_consultation_save:
    path:     /save
    defaults: { _controller: PSConsultationBundle:Consultation:save }
   
    
ps_consultation_view:
    path:     /view/{id}
    defaults: { _controller: PSConsultationBundle:Consultation:view }
    requirements:
        id: \d+