ps_consultation_homepage:
    path:     /
    defaults: { _controller: PSConsultationBundle:Consultation:index }

ps_consultation_add_or_edit:
    path:     /add_or_edit/{patient_id}/{consultation_id}
    defaults: 
        _controller: PSConsultationBundle:Consultation:addOrEdit 
        consultation_id: -1
    requirements:
        patient_id: \d+
        consultation_id: \d+