<?php

namespace PS\CustomerBundle\Repository;

/**
 * FATHERRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FATHERRepository extends \Doctrine\ORM\EntityRepository
{
}
