<?php

namespace PS\CustomerBundle\Repository;

/**
 * MotherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotherRepository extends \Doctrine\ORM\EntityRepository
{
}
