<?php

namespace PS\CustomerBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPatientWithParentsAndAddress() 
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->leftJoin('p.mother', 'm')
            ->leftJoin('p.father', 'f')
            ->leftJoin('p.address', 'addr')
            
            ->addSelect('m')
            ->addSelect('f')
            ->addSelect('addr')
        ;
        
        return $qb->getQuery()->getResult();
        
    }
}
