<?php

namespace PS\CustomerBundle\Repository;

/**
 * TutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorRepository extends \Doctrine\ORM\EntityRepository
{
}
